### ISSUE TITLE
GPU RAM increasing without bound while training CT-ED-45

### ISSUE THREAD

**Issue by EaswarGn** [sgrvinod/chess-transformers#16]
I am training the CT-ED-45 model with the exact same code and dataset used in this repo, except that I changed the batch size to 16 and num_workers to 1 in the configs. I am training on a T4 GPU in google colab, and after 800 or so steps all the GPU RAM (15GB) is used up and I get an error saying that Pytorch isn't able to allocate anymore memory. During training, the GPU RAM keeps increasing with each step without bound, I'm not sure why.

**Comment by sgrvinod** [comment]
Hi, I think this might be because `ChessDataset` in train/datasets.py is using a list of all indices called `self.indices`. With a large dataset, this list gets very large and can lead to the increasing RAM problem, if I remember right. You'll see that I've added a `TODO` in the code there.

If you look at `ChessDatasetFT` in the same file, I don't use `self.indices`. I use `self.first_index`. If you make the corresponding change in `ChessDataset`, this should fix your issue. You can take a look at the history of the file to see how I made the change in `ChessDataset`.

Hope this helps.

**Comment by sgrvinod** [comment]
Hi, I think this might be because `ChessDataset` in train/datasets.py is using a list of all indices called `self.indices`. With a large dataset, this list gets very large and can lead to the increasing RAM problem, if I remember right. You'll see that I've added a `TODO` in the code there.

If you look at `ChessDatasetFT` in the same file, I don't use `self.indices`. I use `self.first_index`. If you make the corresponding change in `ChessDataset`, this should fix your issue. You can take a look at the history of the file to see how I made the change in `ChessDataset`.

Hope this helps.

I didn't face this issue when I trained CT-ED-45, but it happened when using a much bigger dataset for CT-EFT-85. I fixed it in `ChessDatasetFT` but not in `ChessDataset`.

**Comment by EaswarGn** [comment]
Ok, so I updated the `ChessDataset` to mirror the changes made in ChessDatasetFT. This is the new code:
```python
class ChessDataset(Dataset):
    def __init__(self, data_folder, h5_file, split, n_moves=None, **unused):
        """
        Init.

        Args:

            datasets (list): A list of tuples, each containing:

                (dict): A data configuration representing the
                dataset.

                (str): The data split. One of "train", "val", or
                None, which means that all datapoints will be
                included.

            n_moves (int, optional): Number of moves into the future to
            return. Defaults to None, which means that all moves in the
            H5 data column will be returned.
        """
        if n_moves is not None:
            assert n_moves > 0

        # Open table in H5 file
        self.h5_file = tb.open_file(os.path.join(data_folder, h5_file), mode="r")
        self.encoded_table = self.h5_file.root.encoded_data
        self.split = split

        # Create indices
        if split == "train":
            self.first_index = 0
        elif split == "val":
            self.first_index = self.encoded_table.attrs.val_split_index
        elif split is None:
            self.first_index = 0
        else:
            raise NotImplementedError

        self.n_moves = 10

    def __getitem__(self, i):
        turns = torch.IntTensor([self.encoded_table[self.first_index + i]["turn"]])
        white_kingside_castling_rights = torch.IntTensor(
            [self.encoded_table[self.first_index + i]["white_kingside_castling_rights"]]
        )  # (1)
        white_queenside_castling_rights = torch.IntTensor(
            [self.encoded_table[self.first_index + i]["white_queenside_castling_rights"]]
        )  # (1)
        black_kingside_castling_rights = torch.IntTensor(
            [self.encoded_table[self.first_index + i]["black_kingside_castling_rights"]]
        )  # (1)
        black_queenside_castling_rights = torch.IntTensor(
            [self.encoded_table[self.first_index + i]["black_queenside_castling_rights"]]
        )  # (1)
        board_position = torch.IntTensor(
            self.encoded_table[self.first_index + i]["board_position"]
        )  # (64)
        moves = torch.LongTensor(
            self.encoded_table[self.first_index + i]["moves"][: self.n_moves + 1]
        )  # (n_moves + 1)
        length = torch.LongTensor(
            [self.encoded_table[self.first_index + i]["length"]]
        ).clamp(
            max=self.n_moves
        )  # (1), value <= n_moves

        return {
            "turns": turns,
            "white_kingside_castling_rights": white_kingside_castling_rights,
            "white_queenside_castling_rights": white_queenside_castling_rights,
            "black_kingside_castling_rights": black_kingside_castling_rights,
            "black_queenside_castling_rights": black_queenside_castling_rights,
            "board_positions": board_position,
            "moves": moves,
            "lengths": length,
        }

    def __len__(self):
        if self.split == "train":
            return self.encoded_table.attrs.val_split_index
        elif self.split == "val":
            return self.encoded_table.nrows - self.encoded_table.attrs.val_split_index
        elif self.split is None:
            self.encoded_table.nrows
        else:
            raise NotImplementedError
```

But I am still facing the same issue from above.

**Comment by EaswarGn** [comment]
Still need help with this issue, please. ^^^

**Comment by sgrvinod** [comment]
I'll test this on my PC on Monday and see if I can reproduce the same problem

**Comment by sgrvinod** [comment]
Yes, I'm facing the same issue, not sure why yet. I didn't have this problem earlier (when I first trained this model). So I guess it's because of a change made later. Unfortunately, I can't take a very deep look today as I'm sick, so I hope to fix this in the next few days.

**Comment by EaswarGn** [comment]
Sure, get well soon. Let me know when you find what the problem is.

**Comment by sgrvinod** [comment]
Okay, so I found that the issue occurs due to [this line](https://github.com/sgrvinod/chess-transformers/blob/2acccd1a81985419b9367918d57541fc0f6f0acd/chess_transformers/transformers/modules.py#L103):

```python
        # Is this self-attention?
        self_attention = torch.equal(key_value_sequences, query_sequences)
```

I'm checking this during forward propagation to find out whether self-attention or cross-attention is being performed in the multi-head attention module. During [cross-attention (in the decoder)](https://github.com/sgrvinod/chess-transformers/blob/2acccd1a81985419b9367918d57541fc0f6f0acd/chess_transformers/transformers/modules.py#L706), this evaluates to `False`. And when it evaluates to `False`, it causes a memory leak. 

Why? Not for any straightforward or obvious reason; it seems to be a quirk of PyTorch's compilation (when the model is compiled using `torch.compile()`) with the current version of PyTorch.

The quickest fix is to disable dynamic shape tracing during compilation by passing the argument `dynamic=False` [here](https://github.com/sgrvinod/chess-transformers/blob/2acccd1a81985419b9367918d57541fc0f6f0acd/chess_transformers/train/train.py#L88).  So, you can set `DYNAMIC_COMPILATION = False` [here](https://github.com/sgrvinod/chess-transformers/blob/2acccd1a81985419b9367918d57541fc0f6f0acd/chess_transformers/configs/models/CT-ED-45.py#L53). There's probably a better or more elegant fix, but I suggest doing this for now. Alternatively, you can also disable compilation entirely by setting `DISABLE_COMPILATION = True` [here](https://github.com/sgrvinod/chess-transformers/blob/2acccd1a81985419b9367918d57541fc0f6f0acd/chess_transformers/configs/models/CT-ED-45.py#L51), but this may also increase your training step times. On an RTX 2080 Ti, this increases step times from 0.9 s/step to 2.3 s/step: a 2.5x slowdown. 

Let me know if this fixes it! I'll push a change in some time.

**Comment by sgrvinod** [comment]
Fixed in #17, please reopen if needed.
